// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  canvasLayerList: string;
  closeAvailableCanvasLayerImagesButton: string;
  condense: string;
  container: string;
  exportButton: string;
  exporting: string;
  fixedHeight: string;
  inputRange: string;
  inputs: string;
  margin: string;
  svg: string;
}
export const cssExports: CssExports;
export default cssExports;
