// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  PCReverse: string;
  canvasElements: string;
  canvasLayerList: string;
  closeAvailableCanvasLayerImagesButton: string;
  container: string;
  disabled: string;
  editorElements: string;
  exportButton: string;
  exporting: string;
  fixedHeight: string;
  inputRange: string;
  inputs: string;
  margin: string;
  parentFlex: string;
  renderInputs: string;
  svg: string;
}
export const cssExports: CssExports;
export default cssExports;
