// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  canvasLayerList: string;
  closeLayerMenuButton: string;
  container: string;
  inputs: string;
  svg: string;
}
export const cssExports: CssExports;
export default cssExports;
