// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  background: string;
  children: string;
  container: string;
  errorContainer: string;
  errorMessage: string;
  hidden: string;
  okButton: string;
}
export const cssExports: CssExports;
export default cssExports;
