// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  column: string;
  container: string;
  description: string;
  label: string;
}
export const cssExports: CssExports;
export default cssExports;
