// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  background: string;
  container: string;
  message: string;
}
export const cssExports: CssExports;
export default cssExports;
