// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'children': string;
  'container': string;
  'hidden': string;
}
export const cssExports: CssExports;
export default cssExports;
