export enum GOOGLE_ANALYTICS {
  CANVAS = "CANVAS"
}

export enum GOOGLE_ANALYTICS_ACTION {
  CANVAS_BASE_LAYER_ADD = "Action: CANVAS_BASE_LAYER/ADD",
  CANVAS_EXPORT = "Action: CANVAS/EXPORT",
  CANVAS_NORMAL_LAYER_ADD = "Action: CANVAS_NORMAL_LAYER/ADD",
  CANVAS_NORMAL_LAYER_REMOVE = "Action: CANVAS_NORMAL_LAYER/REMOVE"
}
