// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'canvasLayer': string;
  'container': string;
  'display': string;
  'emphasis': string;
  'imageContainer': string;
  'removeButton': string;
}
export const cssExports: CssExports;
export default cssExports;
