// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  addButton: string;
  canvasLayer: string;
  canvasLayerContainer: string;
  container: string;
  emphasis: string;
}
export const cssExports: CssExports;
export default cssExports;
