// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  canvasLayer: string;
  container: string;
  emphasis: string;
}
export const cssExports: CssExports;
export default cssExports;
