// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closeInformationButton': string;
  'contents': string;
}
export const cssExports: CssExports;
export default cssExports;
